############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about"
weight = 2

[[main]]
name = "Services"
url = "services"
weight = 3

[[main]]
name = "Blog"
url = "blog"
weight = 4

[[main]]
name = "Contact"
url = "contact"
weight = 5

# footer menu
[[footer]]
name = "About"
url = "about"
weight = 1

[[footer]]
name = "Services"
url = "services"
weight = 2

[[footer]]
name = "Blog"
url = "blog"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "pages/privacy-policy"
weight = 4

[[footer]]
name = "Contact"
url = "contact"
weight = 5

